const TOTAL=5, KEY='thermorel-progress-v1';
const ACCOUNT_KEY='thermorel-account-v1';
const db=window.supabase?.createClient('https://zzowexahijdlupfurgcs.supabase.co','sb_publishable_jvtfEALEbtnzKM5YLivUAQ_CO3TAZXF');
const E=Object.fromEntries(['target','targetChange','timer','timerNote','mainButton','restartButton','shareButton','accountButton','accountDialog','accountForm','accountTitle','accountCopy','playerName','playerPin','accountError','accountSubmit','accountToggle','createRoom','joinRoom','roomCode','roomStatus','result','score','round','combo','soloMode','versusMode','bestScore','bestNote','leaderboard','achievementList'].map(x=>[x,document.querySelector('#'+x)]));
const badges=[['first','FIRST HEAT','Finish one game'],['score','300 CLUB','Score 300 points'],['combo','HOT STREAK','Reach a 3x combo'],['perfect','ZERO ERROR','Get a Perfect']];
let p=load(),s;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{scores:[],achievements:[]}}catch{return{scores:[],achievements:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(p))} function rnd(){return Math.floor(Math.random()*6)+5}
function fresh(mode=s?.mode||'solo'){let targets=Array.from({length:TOTAL},rnd);return{mode,phase:1,targets,hideAt:targets.map(t=>Math.max(1,t-(1.2+Math.random()*1.8))),playing:false,score:0,round:1,combo:0,maxCombo:0,perfects:0,finished:false}}
function target(){return s.targets[s.round-1]}
function view(){E.target.textContent=s.finished?'GAME COMPLETE':`${s.mode==='versus'?`P${s.phase} · `:''}TARGET ${target()} SECONDS`;E.score.textContent=s.score;E.round.textContent=`${Math.min(s.round,TOTAL)} / ${TOTAL}`;E.combo.textContent=s.combo;for(const [k,m] of [['soloMode','solo'],['versusMode','versus']]){E[k].classList.toggle('is-selected',s.mode===m);E[k].setAttribute('aria-pressed',s.mode===m)}}
function progress(){E.bestScore.textContent=p.scores[0]?.score||0;E.bestNote.textContent=p.scores[0]?`${p.scores[0].label} · ${p.scores[0].date}`:'Finish a game to set a record.';E.leaderboard.innerHTML=Array.from({length:5},(_,i)=>`<li><span>#${i+1}</span><strong>${p.scores[i]?.score??'—'}</strong></li>`).join('');E.achievementList.innerHTML=badges.map(([id,a,b])=>`<li class="achievement ${p.achievements.includes(id)?'is-unlocked':''}">${a}<small>${b}</small></li>`).join('')}
function say(t,k=''){E.result.textContent=t;E.result.className=`result ${k}`}
function start(){if(s.finished)return;s.playing=true;s.start=performance.now();E.mainButton.textContent='STOP';E.timer.textContent='0.00';E.timer.classList.remove('is-hidden');E.timerNote.hidden=true;E.targetChange.hidden=true;say('Watch the timer — it disappears at a random moment.');requestAnimationFrame(tick)}
function tick(now){if(!s.playing)return;let time=(now-s.start)/1000;E.timer.textContent=time.toFixed(2);if(time>=s.hideAt[s.round-1]){E.timer.classList.add('is-hidden');E.timerNote.hidden=false}requestAnimationFrame(tick)}
function rate(d){if(d<.005)return['PERFECT!',100,'is-perfect',1,1];if(d<.1)return['GREAT!',80,'is-great',1,0];if(d<.3)return['GOOD',50,'is-great',0,0];if(d<.5)return['BAD',30,'is-miss',0,0];return['MISS',2,'is-miss',0,0]}
function finish(){let out={score:s.score,maxCombo:s.maxCombo,perfects:s.perfects};if(!p.achievements.includes('first'))p.achievements.push('first');if(out.score>=300&&!p.achievements.includes('score'))p.achievements.push('score');if(out.maxCombo>=3&&!p.achievements.includes('combo'))p.achievements.push('combo');if(out.perfects&&!p.achievements.includes('perfect'))p.achievements.push('perfect');if(s.mode==='versus'&&s.phase===1){s.player1Score=out.score;s.phase=2;s.score=0;s.round=1;s.combo=0;s.maxCombo=0;s.perfects=0;say(`PLAYER 1: ${out.score} POINTS — PLAYER 2, YOUR TURN.`,'is-great');return}p.scores.push({score:out.score,label:s.mode==='versus'?`P${s.phase}`:'SOLO',date:new Date().toLocaleDateString()});p.scores.sort((a,b)=>b.score-a.score);p.scores=p.scores.slice(0,5);save();progress();s.finished=true;E.mainButton.disabled=true;const versus=s.mode==='versus';const winner=out.score===s.player1Score?'DRAW':out.score>s.player1Score?'PLAYER 2 WINS':'PLAYER 1 WINS';say(versus?`${winner} · P1 ${s.player1Score} / P2 ${out.score}`:`GAME OVER — ${out.score} POINTS · ${out.perfects} PERFECT${out.perfects===1?'':'S'}`,'is-perfect')}
function stop(){if(!s.playing)return;s.playing=false;let time=(performance.now()-s.start)/1000,d=Math.abs(target()-time),r=rate(d);s.score+=r[1];s.combo=r[3]?s.combo+1:0;s.maxCombo=Math.max(s.maxCombo,s.combo);s.perfects+=r[4];E.timer.classList.remove('is-hidden');E.timerNote.hidden=true;E.timer.textContent=time.toFixed(2);E.mainButton.textContent='START';say(`${r[0]} +${r[1]} · OFF BY ${d.toFixed(2)}s`,r[2]);s.round++;if(s.round>TOTAL)finish();else{E.targetChange.textContent=`NEXT ROUND · NEW TARGET: ${target()} SECONDS`;E.targetChange.hidden=false}view()}
function reset(){s=fresh(s?.mode);E.mainButton.disabled=false;E.mainButton.textContent='START';E.timer.textContent='0.00';E.timer.classList.remove('is-hidden');E.timerNote.hidden=true;E.targetChange.hidden=true;say(s.mode==='versus'?'Player 1 starts. Both players receive the same targets; the timer hides at a random moment.':'Press START. The timer hides at a random moment each round.');view()}
function mode(m){if(!s.playing){s=fresh(m);reset()}}
E.mainButton.onclick=()=>s.playing?stop():start();E.restartButton.onclick=reset;E.soloMode.onclick=()=>mode('solo');E.versusMode.onclick=()=>mode('versus');E.shareButton.onclick=async()=>{const share={title:'THERMOREL',text:'Can you beat my hidden-timer score?',url:location.href};try{if(navigator.share)await navigator.share(share);else{await navigator.clipboard.writeText(location.href);E.shareButton.textContent='COPIED!';setTimeout(()=>E.shareButton.textContent='↗ SHARE',1300)}}catch{}};document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&e.target===document.body){e.preventDefault();E.mainButton.click()}});reset();progress();
function code(){return Array.from({length:6},()=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*32)]).join('')}
function roomMsg(t){E.roomStatus.textContent=t}
async function createRoom(){if(!db)return roomMsg('Online mode is loading.');const room=code(),targets=Array.from({length:TOTAL},rnd);const {error}=await db.from('rooms').insert({code:room,targets,status:'waiting'});if(error)return roomMsg('Could not create room. Try again.');s.mode='versus';reset();s.targets=targets;view();E.roomCode.value=room;roomMsg(`ROOM ${room} CREATED — share this code.`);db.channel('room-'+room).on('postgres_changes',{event:'UPDATE',schema:'public',table:'rooms',filter:'code=eq.'+room},p=>roomMsg(p.new.status==='playing'?'OPPONENT JOINED — START!':'Room updated.')).subscribe()}
async function joinRoom(){if(!db)return roomMsg('Online mode is loading.');const room=E.roomCode.value.trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(room))return roomMsg('Enter a 6-digit code.');const {data,error}=await db.from('rooms').update({status:'playing',updated_at:new Date().toISOString()}).eq('code',room).select().single();if(error||!data)return roomMsg('Room not found.');s.targets=data.targets; s.mode='versus'; reset(); s.targets=data.targets; roomMsg('JOINED! Same targets loaded — START!')}
E.mainButton.onclick=()=>s.playing?stop():start();E.restartButton.onclick=reset;E.soloMode.onclick=()=>mode('solo');E.versusMode.onclick=()=>mode('versus');E.createRoom.onclick=createRoom;E.joinRoom.onclick=joinRoom;E.roomCode.oninput=()=>E.roomCode.value=E.roomCode.value.toUpperCase();E.shareButton.onclick=async()=>{const share={title:'THERMOREL',text:'Can you beat my hidden-timer score?',url:location.href};try{if(navigator.share)await navigator.share(share);else{await navigator.clipboard.writeText(location.href);E.shareButton.textContent='COPIED!';setTimeout(()=>E.shareButton.textContent='↗ SHARE',1300)}}catch{}};document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&e.target===document.body){e.preventDefault();E.mainButton.click()}});reset();progress();
let loginMode=false;function account(){try{return JSON.parse(localStorage.getItem(ACCOUNT_KEY))}catch{return null}}function openAccount(force=false){const a=account();loginMode=!!a&&!force;E.accountTitle.textContent=loginMode?'LOG IN':'CREATE ACCOUNT';E.accountCopy.textContent=loginMode?'Enter your nickname and PIN to continue.':'Pick a nickname and a 4-digit PIN. No email needed.';E.accountSubmit.textContent=loginMode?'LOG IN':'CREATE & PLAY';E.accountToggle.textContent=loginMode?'New player? CREATE ACCOUNT':'Already have an account? LOG IN';E.playerName.value=loginMode?a.name:'';E.playerPin.value='';E.accountError.textContent='';E.accountDialog.showModal()}function submitAccount(e){e.preventDefault();const name=E.playerName.value.trim(),pin=E.playerPin.value;if(!name||!/^\d{4}$/.test(pin))return E.accountError.textContent='Enter a nickname and a 4-digit PIN.';const a=account();if(loginMode&&(!a||a.name!==name||a.pin!==pin))return E.accountError.textContent='Nickname or PIN is incorrect.';if(!loginMode)localStorage.setItem(ACCOUNT_KEY,JSON.stringify({name,pin}));E.accountDialog.close();E.accountButton.textContent=name.toUpperCase()}E.accountButton.onclick=()=>openAccount(true);E.accountForm.addEventListener('submit',submitAccount);E.accountToggle.onclick=()=>{loginMode=!loginMode;openAccount(!loginMode)};const currentAccount=account();if(currentAccount)E.accountButton.textContent=currentAccount.name.toUpperCase();else setTimeout(()=>openAccount(false),250);document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&e.target===document.body){e.preventDefault();E.mainButton.click()}});reset();progress();
