const TOTAL=5, KEY='thermorel-progress-v1';
const ACCOUNT_KEY='thermorel-account-v2';
const db=window.supabase?.createClient('https://zzowexahijdlupfurgcs.supabase.co','sb_publishable_jvtfEALEbtnzKM5YLivUAQ_CO3TAZXF');
const E=Object.fromEntries(['target','targetChange','timer','timerFrame','timerNote','mainButton','restartButton','shareButton','accountButton','accountDialog','accountForm','accountTitle','accountCopy','playerName','playerPin','accountError','accountSubmit','accountToggle','createRoom','joinRoom','roomCode','roomStatus','result','score','round','combo','soloMode','versusMode','progressToggle','metaBoard','bestScore','bestNote','leaderboard','achievementList','onlineButton','spectateButton','onlineOverlay','onlineChoice','onlineClose','onlineCreate','onlineJoin','onlineCreateScreen','createBack','createPublic','createSecret','onlineLoadingScreen','onlineCreateCancel','onlineJoinScreen','joinBack','onlineRoomCode','onlineJoinConfirm','onlineError','spectateScreen','spectateBack','spectateRoomCode','spectateJoin','spectateError','publicRoomList','onlineLobby','lobbyExit','lobbyStatus','lobbyCode','lobbyHelp','rosterLabel','playerRosterList','gameStart','opponentPanel','opponentName','opponentTimer','opponentScore','opponentRound','onlineResultScreen','onlineResultTitle','onlineResultScore','onlineResultCopy','onlineResultBack','spectatorView','spectatorExit','spectatorViewTitle','spectatorViewCopy','spectatorGrid','artSticker'].map(x=>[x,document.querySelector('#'+x)]));
const badges=[['first','FIRST HEAT','Finish one game'],['score','300 CLUB','Score 300 points'],['combo','HOT STREAK','Reach a 3x combo'],['perfect','ZERO ERROR','Get a Perfect']];
let p=load(),s;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{scores:[],achievements:[]}}catch{return{scores:[],achievements:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(p))} function rnd(){return Math.floor(Math.random()*6)+5}
function fresh(mode=s?.mode||'solo'){let targets=Array.from({length:TOTAL},rnd);return{mode,phase:1,targets,hideAt:targets.map(t=>Math.max(1,t-(1.2+Math.random()*1.8))),playing:false,score:0,round:1,combo:0,maxCombo:0,perfects:0,finished:false}}
function target(){return s.targets[s.round-1]}
function view(){E.target.textContent=s.finished?'GAME COMPLETE':`${s.mode==='versus'?`P${s.phase} · `:''}TARGET ${target()} SECONDS`;E.score.textContent=s.score;E.round.textContent=`${Math.min(s.round,TOTAL)} / ${TOTAL}`;E.combo.textContent=s.combo;for(const [k,m] of [['soloMode','solo'],['versusMode','versus']]){E[k].classList.toggle('is-selected',s.mode===m);E[k].setAttribute('aria-pressed',s.mode===m)}}
function progress(){E.bestScore.textContent=p.scores[0]?.score||0;E.bestNote.textContent=p.scores[0]?`${p.scores[0].label} · ${p.scores[0].date}`:'Finish a game to set a record.';E.leaderboard.innerHTML=Array.from({length:5},(_,i)=>`<li><span>#${i+1}</span><strong>${p.scores[i]?.score??'—'}</strong></li>`).join('');E.achievementList.innerHTML=badges.map(([id,a,b])=>`<li class="achievement ${p.achievements.includes(id)?'is-unlocked':''}">${a}<small>${b}</small></li>`).join('')}
function say(t,k=''){E.result.textContent=t;E.result.className=`result ${k}`}
let obscurePause,obscureSpin;
function clearTimerObscure(){clearTimeout(obscurePause);clearTimeout(obscureSpin);E.timer.classList.remove('is-hidden');E.timerFrame.classList.remove('is-obscured','is-blackout','is-paused','is-spinning');E.timerNote.hidden=true}
function obscureTimer(){if(E.timerFrame.classList.contains('is-obscured'))return;E.timerFrame.classList.add('is-obscured');E.timerNote.textContent='STICKERS APPROACHING…';E.timerNote.hidden=false;obscurePause=setTimeout(()=>{E.timerFrame.classList.add('is-blackout','is-paused');E.timer.classList.add('is-hidden');E.timerNote.textContent='TIMER LOST…';obscureSpin=setTimeout(()=>{E.timerFrame.classList.remove('is-paused');E.timerFrame.classList.add('is-spinning');E.timerNote.textContent='TIMER LOST — stop when you think the target time has arrived.'},560)},1050)}
function start(){if(s.finished)return;s.playing=true;s.start=performance.now();E.mainButton.textContent='STOP';E.timer.textContent='0.00';clearTimerObscure();E.targetChange.hidden=true;say('Trust your sense of time. Stop at the target.');requestAnimationFrame(tick)}
function tick(now){if(!s.playing)return;let time=(now-s.start)/1000;E.timer.textContent=time.toFixed(2);if(time>=s.hideAt[s.round-1])obscureTimer();sendRivalState(time);requestAnimationFrame(tick)}
function rate(d){if(d<.005)return['PERFECT!',100,'is-perfect',1,1];if(d<.1)return['GREAT!',80,'is-great',1,0];if(d<.3)return['GOOD',50,'is-great',0,0];if(d<.5)return['BAD',30,'is-miss',0,0];return['MISS',2,'is-miss',0,0]}
function finish(){let out={score:s.score,maxCombo:s.maxCombo,perfects:s.perfects};if(!p.achievements.includes('first'))p.achievements.push('first');if(out.score>=300&&!p.achievements.includes('score'))p.achievements.push('score');if(out.maxCombo>=3&&!p.achievements.includes('combo'))p.achievements.push('combo');if(out.perfects&&!p.achievements.includes('perfect'))p.achievements.push('perfect');if(s.mode==='versus'&&s.phase===1&&!isOnlineMatch()){s.player1Score=out.score;s.phase=2;s.score=0;s.round=1;s.combo=0;s.maxCombo=0;s.perfects=0;say(`PLAYER 1: ${out.score} POINTS — PLAYER 2, YOUR TURN.`,'is-great');return}p.scores.push({score:out.score,label:isOnlineMatch()?'ONLINE':s.mode==='versus'?`P${s.phase}`:'SOLO',date:new Date().toLocaleDateString()});p.scores.sort((a,b)=>b.score-a.score);p.scores=p.scores.slice(0,5);save();progress();s.finished=true;E.mainButton.disabled=true;if(isOnlineMatch()){finishOnlineMatch(out);return}const versus=s.mode==='versus';const winner=out.score===s.player1Score?'DRAW':out.score>s.player1Score?'PLAYER 2 WINS':'PLAYER 1 WINS';say(versus?`${winner} · P1 ${s.player1Score} / P2 ${out.score}`:`GAME OVER — ${out.score} POINTS · ${out.perfects} PERFECT${out.perfects===1?'':'S'}`,'is-perfect')}
function stop(){if(!s.playing)return;s.playing=false;let time=(performance.now()-s.start)/1000,d=Math.abs(target()-time),r=rate(d);s.score+=r[1];s.combo=r[3]?s.combo+1:0;s.maxCombo=Math.max(s.maxCombo,s.combo);s.perfects+=r[4];document.dispatchEvent(new CustomEvent('thermorel:round-result',{detail:{label:r[0],combo:s.combo,accurate:!!r[3]}}));clearTimerObscure();E.timer.textContent=time.toFixed(2);E.mainButton.textContent='START';say(`${r[0]} +${r[1]} · OFF BY ${d.toFixed(2)}s`,r[2]);s.round++;if(s.round>TOTAL)finish();else{E.targetChange.textContent=`NEXT ROUND · NEW TARGET: ${target()} SECONDS`;E.targetChange.hidden=false}view();lastRivalBroadcast=0;sendRivalState(time)}
function reset(){s=fresh(s?.mode);E.mainButton.disabled=false;E.mainButton.textContent='START';E.timer.textContent='0.00';clearTimerObscure();E.targetChange.hidden=true;say(s.mode==='versus'?'Player 1 starts. Both players receive the same targets.':'Press START. Stop as close to the target as you can.');view()}
function mode(m,writeRoute=true){if(s.playing)return;if(writeRoute){goRoute(m);return}s=fresh(m);reset()}
E.mainButton.onclick=()=>s.playing?stop():start();E.restartButton.onclick=reset;E.soloMode.onclick=()=>mode('solo');E.versusMode.onclick=()=>mode('versus');E.shareButton.onclick=async()=>{const share={title:'THERMOREL',text:'Can you beat my hidden-timer score?',url:location.href};try{if(navigator.share)await navigator.share(share);else{await navigator.clipboard.writeText(location.href);E.shareButton.textContent='COPIED!';setTimeout(()=>E.shareButton.textContent='↗ SHARE',1300)}}catch{}};document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&e.target===document.body){e.preventDefault();E.mainButton.click()}});reset();progress();
function code(){return Array.from({length:6},()=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*32)]).join('')}
function roomMsg(t){E.roomStatus.textContent=t}
async function createRoom(){if(!db)return roomMsg('Online mode is loading.');const room=code(),targets=Array.from({length:TOTAL},rnd);const {error}=await db.from('rooms').insert({code:room,targets,status:'waiting'});if(error)return roomMsg('Could not create room. Try again.');s.mode='versus';reset();s.targets=targets;view();E.roomCode.value=room;roomMsg(`ROOM ${room} CREATED — share this code.`);db.channel('room-'+room).on('postgres_changes',{event:'UPDATE',schema:'public',table:'rooms',filter:'code=eq.'+room},p=>roomMsg(p.new.status==='playing'?'OPPONENT JOINED — START!':'Room updated.')).subscribe()}
async function joinRoom(){if(!db)return roomMsg('Online mode is loading.');const room=E.roomCode.value.trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(room))return roomMsg('Enter a 6-digit code.');const {data,error}=await db.from('rooms').update({status:'playing',updated_at:new Date().toISOString()}).eq('code',room).select().single();if(error||!data)return roomMsg('Room not found.');s.targets=data.targets; s.mode='versus'; reset(); s.targets=data.targets; roomMsg('JOINED! Same targets loaded — START!')}
E.mainButton.onclick=()=>s.playing?stop():start();E.restartButton.onclick=reset;E.soloMode.onclick=()=>mode('solo');E.versusMode.onclick=()=>mode('versus');E.createRoom.onclick=createRoom;E.joinRoom.onclick=joinRoom;E.roomCode.oninput=()=>E.roomCode.value=E.roomCode.value.toUpperCase();E.shareButton.onclick=async()=>{const share={title:'THERMOREL',text:'Can you beat my hidden-timer score?',url:location.href};try{if(navigator.share)await navigator.share(share);else{await navigator.clipboard.writeText(location.href);E.shareButton.textContent='COPIED!';setTimeout(()=>E.shareButton.textContent='↗ SHARE',1300)}}catch{}};document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&e.target===document.body){e.preventDefault();E.mainButton.click()}});reset();progress();
let loginMode=false;function account(){try{return JSON.parse(localStorage.getItem(ACCOUNT_KEY))}catch{return null}}function renderAccount(){const a=account();E.accountTitle.textContent=loginMode?'LOG IN':'CREATE ACCOUNT';E.accountCopy.textContent=loginMode?'Enter your nickname and PIN to continue.':'Pick a nickname and a 4-digit PIN. No email needed.';E.accountSubmit.textContent=loginMode?'LOG IN':'CREATE & PLAY';E.accountToggle.textContent=loginMode?'New player? CREATE ACCOUNT':'Already have an account? LOG IN';E.playerName.value=loginMode&&a?a.name:'';E.playerPin.value='';E.accountError.textContent=''}function openAccount(){loginMode=!!account();renderAccount();if(!E.accountDialog.open)E.accountDialog.showModal()}function submitAccount(e){e.preventDefault();const name=E.playerName.value.trim(),pin=E.playerPin.value;if(!name||!/^\d{4}$/.test(pin))return E.accountError.textContent='Enter a nickname and a 4-digit PIN.';const a=account();if(loginMode&&(!a||a.name!==name||a.pin!==pin))return E.accountError.textContent='Nickname or PIN is incorrect.';if(!loginMode)localStorage.setItem(ACCOUNT_KEY,JSON.stringify({name,pin}));E.accountDialog.close();E.accountButton.textContent=name.toUpperCase()}E.accountButton.onclick=openAccount;E.accountForm.addEventListener('submit',submitAccount);E.accountToggle.onclick=()=>{loginMode=!loginMode;renderAccount()};const currentAccount=account();if(currentAccount)E.accountButton.textContent=currentAccount.name.toUpperCase();else setTimeout(openAccount,250);document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&e.target===document.body){e.preventDefault();E.mainButton.click()}});reset();progress();
E.progressToggle.onclick=()=>{const open=E.metaBoard.hidden;E.metaBoard.hidden=!open;E.progressToggle.setAttribute('aria-expanded',String(open));E.progressToggle.textContent=open?'▴ PROGRESS':'▾ PROGRESS'};
function scheduleArtMotion(){if(!E.artSticker)return;setTimeout(()=>{if(!document.body.classList.contains('online-playing')){E.artSticker.currentTime=0;E.artSticker.closest('.art-panel').classList.add('is-moving');E.artSticker.play().catch(()=>{E.artSticker.closest('.art-panel').classList.remove('is-moving');scheduleArtMotion()})}else scheduleArtMotion()},10000+Math.random()*20000)}
if(E.artSticker){E.artSticker.addEventListener('ended',()=>{E.artSticker.closest('.art-panel').classList.remove('is-moving');scheduleArtMotion()});scheduleArtMotion()}

const ONLINE_ID_KEY='thermorel-online-id-v1';
const onlineId=localStorage.getItem(ONLINE_ID_KEY)||(()=>{const id=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem(ONLINE_ID_KEY,id);return id})();
let onlineRoom='',onlineRole='',onlineTargets=[],onlineChannel,onlineStartAt=0,lastRivalBroadcast=0,createRequest=0,onlineInfo=null,liveStates={},spectatorPulse=0;
function safePlayerName(){return (account()?.name||'PLAYER').replace(/[|:]/g,'').slice(0,12)||'PLAYER'}
function isOnlineMatch(){return !!onlineRoom&&document.body.classList.contains('online-playing')}
function roomData(status=''){try{const room=JSON.parse(status);if(room?.v===2)return{players:[],spectators:[],results:{},visibility:'secret',stage:'waiting',startAt:0,...room}}catch{}const [stage='waiting',host='',guest='',startAt='']=status.split('|');const decode=x=>{try{return decodeURIComponent(x||'')}catch{return''}};const players=[host&&{id:'legacy-host',name:decode(host)},guest&&{id:'legacy-guest',name:decode(guest)}].filter(Boolean);return{v:1,stage,players,spectators:[],results:{},visibility:'secret',startAt:Number(startAt)||0}}
function roomStatus(info){return JSON.stringify({v:2,stage:info.stage,hostId:info.hostId,players:info.players||[],spectators:info.spectators||[],results:info.results||{},visibility:info.visibility||'secret',startAt:info.startAt||0})}
function roomPlayer(){return{id:onlineId,name:safePlayerName()}}
function roomHash(kind,pass){return `${kind}&pass=${encodeURIComponent(pass)}`}
function parseHash(){const [kind,...parts]=location.hash.slice(1).split('&');return{kind:(kind||'').toLowerCase(),pass:new URLSearchParams(parts.join('&')).get('pass')?.toUpperCase()||''}}
async function updateRoom(info){onlineInfo=info;return db.from('rooms').update({status:roomStatus(info),updated_at:new Date().toISOString()}).eq('code',onlineRoom)}
async function patchRoom(change){const {data}=await db.from('rooms').select('status,targets').eq('code',onlineRoom).single();if(!data)return;const info=roomData(data.status);change(info);onlineTargets=data.targets||onlineTargets;await updateRoom(info)}
function subscribeOnlineRoom(){onlineChannel?.unsubscribe?.();onlineChannel=db.channel('online-'+onlineRoom).on('broadcast',{event:'rival-state'},event=>renderRivalState(event.payload)).on('postgres_changes',{event:'UPDATE',schema:'public',table:'rooms',filter:'code=eq.'+onlineRoom},event=>syncOnlineRoom(event.new)).subscribe()}
function updateLobby(info){const players=info.players||[];E.lobbyCode.textContent=onlineRoom;E.rosterLabel.textContent=`PLAYERS ${players.length} / 8`;E.playerRosterList.innerHTML=players.map((player,index)=>`<div class="player-row">${player.id===info.hostId?'HOST':'PLAYER '+(index+1)} · ${player.name}</div>`).join('')||'<div class="player-row">WAITING FOR PLAYER</div>';const ready=players.length>=2;E.lobbyStatus.textContent=ready?'PLAYERS READY':'WAITING FOR PLAYERS';E.lobbyHelp.textContent=`${info.visibility==='public'?'PUBLIC':'SECRET'} SPECTATORS · ${info.spectators?.length||0} / 10 WATCHING`;E.gameStart.hidden=!(onlineRole==='host'&&ready)}
function showLobby(info){document.body.classList.remove('online-playing','spectator-viewing');document.body.classList.add('online-lobby-open');E.onlineOverlay.hidden=true;E.onlineLobby.hidden=false;updateLobby(info)}
function showOnlineGame(info={}){if(document.body.classList.contains('online-playing')&&onlineStartAt===info.startAt)return;document.body.classList.remove('online-lobby-open','spectator-viewing');document.body.classList.add('online-playing');E.onlineLobby.hidden=true;E.onlineResultScreen.hidden=true;liveStates={};s.mode='versus';reset();s.targets=onlineTargets;view();const other=info.players?.find(player=>player.id!==onlineId);E.opponentName.textContent=other?.name||'PLAYERS LIVE';E.opponentTimer.textContent='0.00';E.opponentScore.textContent='0';E.opponentRound.textContent='1 / 5';onlineStartAt=info.startAt||Date.now()+5000;E.mainButton.disabled=true;E.mainButton.textContent='SYNCING';const countdown=()=>{const left=Math.max(0,onlineStartAt-Date.now());say(left?`MATCH STARTS IN ${(left/1000).toFixed(1)}…`:'GO!','is-perfect');if(left)return setTimeout(countdown,80);E.mainButton.disabled=false;start()};countdown()}
function renderSpectator(){if(!document.body.classList.contains('spectator-viewing')||!onlineInfo)return;E.spectatorViewTitle.textContent=`ROOM ${onlineRoom}`;E.spectatorViewCopy.textContent=`${onlineInfo.players.length} PLAYERS · ${onlineInfo.spectators.length} / 10 SPECTATORS`;E.spectatorGrid.innerHTML=onlineInfo.players.map(player=>{const state=liveStates[player.id]||{},score=onlineInfo.results[player.id]??state.score??0;return`<article class="spectator-card"><h3>${player.name}</h3><strong>${state.time||'0.00'}</strong><p>${onlineInfo.results[player.id]!==undefined?'FINISHED':state.playing?'PLAYING':'READY'} · SCORE ${score} · ${state.round||'1 / 5'}</p></article>`}).join('')}
function showSpectator(info){document.body.classList.remove('online-lobby-open','online-playing');document.body.classList.add('spectator-viewing');E.onlineOverlay.hidden=true;E.onlineLobby.hidden=true;E.spectatorView.hidden=false;renderSpectator();clearInterval(spectatorPulse);spectatorPulse=setInterval(()=>patchRoom(room=>{room.spectators=(room.spectators||[]).map(viewer=>viewer.id===onlineId?{...viewer,seen:Date.now()}:viewer).filter(viewer=>Date.now()-(viewer.seen||0)<90000)}),30000)}
function syncOnlineRoom(room){const info=roomData(room.status);onlineInfo=info;if(room.targets)onlineTargets=room.targets;if(onlineRole==='spectator'){showSpectator(info);return}if(s?.finished)updateOnlineResult();if(info.stage==='playing'){showOnlineGame(info);return}showLobby(info)}
function hideOnlineScreens(){E.onlineChoice.hidden=true;E.onlineCreateScreen.hidden=true;E.onlineLoadingScreen.hidden=true;E.onlineJoinScreen.hidden=true;E.spectateScreen.hidden=true}
function openOnline(){E.onlineOverlay.hidden=false;hideOnlineScreens();E.onlineChoice.hidden=false;E.onlineError.textContent=''}
function closeOnline(){createRequest++;E.onlineOverlay.hidden=true;hideOnlineScreens()}
function goRoute(route=''){const hash=route?`#${route}`:'';if(location.hash===hash){applyRoute();return}location.hash=hash}
async function openRoomFromHash(pass){if(!/^[A-Z0-9]{6}$/.test(pass))return;if(onlineRole==='spectator'&&onlineRoom===pass){showSpectator(onlineInfo);return}const {data}=await db.from('rooms').select('status,targets').eq('code',pass).single();if(!data)return goRoute('online');const info=roomData(data.status);if(!info.players.some(player=>player.id===onlineId))return goRoute(roomHash('join',pass));onlineRoom=pass;onlineRole=info.hostId===onlineId?'host':'player';onlineTargets=data.targets;onlineInfo=info;subscribeOnlineRoom();syncOnlineRoom(data)}
async function applyRoute(){const {kind,pass}=parseHash();if(kind==='online'){openOnline();return}if(kind==='spectate'){openSpectate();return}if(kind==='join'&&pass){await joinOnline(pass);return}if(kind==='room'&&pass){await openRoomFromHash(pass);return}closeOnline();if(kind==='solo'||kind==='versus')mode(kind,false)}
function chooseCreate(){hideOnlineScreens();E.onlineCreateScreen.hidden=false}
async function createOnline(visibility){if(!db)return;const request=++createRequest,room=code(),targets=Array.from({length:TOTAL},rnd),host=roomPlayer(),info={v:2,stage:'waiting',hostId:host.id,players:[host],spectators:[],results:{},visibility,startAt:0};hideOnlineScreens();E.onlineLoadingScreen.hidden=false;const {error}=await db.from('rooms').insert({code:room,targets,status:roomStatus(info)});if(request!==createRequest)return;if(error){E.onlineLoadingScreen.hidden=true;E.onlineChoice.hidden=false;E.onlineError.textContent='Could not create room. Try again.';return}onlineRoom=room;onlineRole='host';onlineTargets=targets;onlineInfo=info;subscribeOnlineRoom();goRoute(roomHash('room',room));showLobby(info)}
function cancelCreate(){createRequest++;hideOnlineScreens();E.onlineChoice.hidden=false}
function showJoinScreen(){hideOnlineScreens();E.onlineJoinScreen.hidden=false;E.onlineRoomCode.value='';E.onlineError.textContent=''}
async function joinOnline(pass=E.onlineRoomCode.value.trim().toUpperCase()){if(!db)return;if(!/^[A-Z0-9]{6}$/.test(pass)){E.onlineError.textContent='Enter a 6-digit code.';return}const {data,error}=await db.from('rooms').select('status,targets').eq('code',pass).single();if(error||!data){E.onlineError.textContent='Room not found.';return}const info=roomData(data.status);if(info.stage==='playing'){E.onlineError.textContent='Match already started. Use SPECTATE.';return}if(!info.players.some(player=>player.id===onlineId)){if(info.players.length>=8){E.onlineError.textContent='This room is full (8 players).';return}info.players.push(roomPlayer())}onlineRoom=pass;onlineRole=info.hostId===onlineId?'host':'player';onlineTargets=data.targets;onlineInfo=info;const {error:updateError}=await updateRoom(info);if(updateError){E.onlineError.textContent='Could not join. Try again.';return}subscribeOnlineRoom();goRoute(roomHash('room',pass));showLobby(info)}
async function startOnline(){if(onlineRole!=='host'||!onlineRoom||onlineInfo.players.length<2)return;const info={...onlineInfo,stage:'playing',startAt:Date.now()+5000};await updateRoom(info);showOnlineGame(info)}
async function openSpectate(){E.onlineOverlay.hidden=false;hideOnlineScreens();E.spectateScreen.hidden=false;E.spectateError.textContent='';const {data}=await db.from('rooms').select('code,status,targets,updated_at').order('updated_at',{ascending:false}).limit(30);const rooms=(data||[]).map(row=>({row,info:roomData(row.status)})).filter(item=>item.info.v===2&&item.info.visibility==='public'&&item.info.stage!=='finished');E.publicRoomList.innerHTML=rooms.length?rooms.map(({row,info})=>`<div class="public-room"><span>${row.code}<small>${info.players.length}/8 PLAYERS</small></span><button type="button" data-watch="${row.code}">WATCH</button></div>`).join(''):'<p class="online-error">NO PUBLIC ROOMS</p>';E.publicRoomList.querySelectorAll('[data-watch]').forEach(button=>button.onclick=()=>watchRoom(button.dataset.watch))}
async function watchRoom(pass=E.spectateRoomCode.value.trim().toUpperCase()){if(!/^[A-Z0-9]{6}$/.test(pass)){E.spectateError.textContent='Enter a 6-digit code.';return}const {data,error}=await db.from('rooms').select('status,targets').eq('code',pass).single();if(error||!data){E.spectateError.textContent='Room not found.';return}const info=roomData(data.status);if(info.v!==2){E.spectateError.textContent='This is an older room.';return}info.spectators=(info.spectators||[]).filter(viewer=>Date.now()-(viewer.seen||0)<90000);if(!info.spectators.some(viewer=>viewer.id===onlineId)){if(info.spectators.length>=10){E.spectateError.textContent='Spectator seats are full (10).';return}info.spectators.push({id:onlineId,name:safePlayerName(),seen:Date.now()})}onlineRoom=pass;onlineRole='spectator';onlineTargets=data.targets;onlineInfo=info;await updateRoom(info);subscribeOnlineRoom();goRoute(roomHash('room',pass));showSpectator(info)}
function exitLobby(){clearInterval(spectatorPulse);onlineChannel?.unsubscribe?.();onlineChannel=null;onlineRoom='';onlineInfo=null;onlineRole='';document.body.classList.remove('online-lobby-open','online-playing','spectator-viewing');E.onlineLobby.hidden=true;E.spectatorView.hidden=true;E.onlineResultScreen.hidden=true;reset();goRoute('')}
function updateOnlineResult(){const scores=onlineInfo?.results||{},mine=scores[onlineId]??s.score,all=onlineInfo?.players||[];E.onlineResultScreen.hidden=false;E.onlineResultScore.textContent=`${mine} POINTS`;if(all.some(player=>scores[player.id]===undefined)){E.onlineResultTitle.textContent='RESULT READY';E.onlineResultCopy.textContent='YOUR RESULT IS SAVED. WAITING FOR THE OTHER PLAYERS.';return}const rank=1+all.filter(player=>(scores[player.id]??0)>mine).length;E.onlineResultTitle.textContent=rank===1?'YOU WIN!':`RANK ${rank}`;E.onlineResultCopy.textContent=all.map(player=>`${player.name} ${scores[player.id]}PT`).join(' · ')}
function finishOnlineMatch(out){onlineInfo.results={...(onlineInfo.results||{}),[onlineId]:out.score};updateOnlineResult();onlineChannel?.send({type:'broadcast',event:'rival-state',payload:{id:onlineId,name:safePlayerName(),time:E.timer.textContent,score:out.score,round:'5 / 5',playing:false}});patchRoom(room=>{room.results={...(room.results||{}),[onlineId]:out.score}})}
E.onlineButton.onclick=()=>goRoute('online');E.spectateButton.onclick=()=>goRoute('spectate');E.onlineClose.onclick=()=>goRoute('');E.onlineCreate.onclick=chooseCreate;E.createBack.onclick=openOnline;E.createPublic.onclick=()=>createOnline('public');E.createSecret.onclick=()=>createOnline('secret');E.onlineCreateCancel.onclick=cancelCreate;E.onlineJoin.onclick=showJoinScreen;E.joinBack.onclick=openOnline;E.onlineJoinConfirm.onclick=()=>joinOnline();E.onlineRoomCode.oninput=()=>E.onlineRoomCode.value=E.onlineRoomCode.value.toUpperCase();E.spectateBack.onclick=openOnline;E.spectateJoin.onclick=()=>watchRoom();E.spectateRoomCode.oninput=()=>E.spectateRoomCode.value=E.spectateRoomCode.value.toUpperCase();E.gameStart.onclick=startOnline;E.lobbyExit.onclick=exitLobby;E.spectatorExit.onclick=exitLobby;E.onlineResultBack.onclick=exitLobby;window.addEventListener('hashchange',applyRoute);applyRoute();
function sendRivalState(time){if(!onlineChannel||!document.body.classList.contains('online-playing')||performance.now()-lastRivalBroadcast<220)return;lastRivalBroadcast=performance.now();onlineChannel.send({type:'broadcast',event:'rival-state',payload:{id:onlineId,name:safePlayerName(),time:time.toFixed(2),score:s.score,round:`${Math.min(s.round,TOTAL)} / ${TOTAL}`,playing:s.playing}})}
function renderRivalState(state){if(!state||state.id===onlineId)return;liveStates[state.id]=state;const other=Object.values(liveStates)[0];if(other){E.opponentName.textContent=other.name||'OPPONENT';E.opponentTimer.textContent=other.time||'0.00';E.opponentScore.textContent=other.score??0;E.opponentRound.textContent=other.round||'1 / 5'}renderSpectator()}
