const TOTAL=5, KEY='thermorel-progress-v1';
const ACCOUNT_KEY='thermorel-account-v2';
const db=window.supabase?.createClient('https://zzowexahijdlupfurgcs.supabase.co','sb_publishable_jvtfEALEbtnzKM5YLivUAQ_CO3TAZXF');
const E=Object.fromEntries(['target','targetChange','timer','timerFrame','timerNote','mainButton','restartButton','shareButton','accountButton','accountDialog','accountForm','accountTitle','accountCopy','playerName','playerPin','accountError','accountSubmit','accountToggle','createRoom','joinRoom','roomCode','roomStatus','result','score','round','combo','soloMode','versusMode','progressToggle','metaBoard','bestScore','bestNote','leaderboard','achievementList','onlineButton','onlineOverlay','onlineChoice','onlineClose','onlineCreate','onlineJoin','onlineLoadingScreen','onlineCreateCancel','onlineJoinScreen','joinBack','onlineRoomCode','onlineJoinConfirm','onlineError','onlineLobby','lobbyExit','lobbyStatus','lobbyCode','lobbyHelp','hostPlayer','guestPlayer','gameStart','opponentPanel','opponentName','opponentTimer','opponentScore','opponentRound','artSticker'].map(x=>[x,document.querySelector('#'+x)]));
const badges=[['first','FIRST HEAT','Finish one game'],['score','300 CLUB','Score 300 points'],['combo','HOT STREAK','Reach a 3x combo'],['perfect','ZERO ERROR','Get a Perfect']];
let p=load(),s;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{scores:[],achievements:[]}}catch{return{scores:[],achievements:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(p))} function rnd(){return Math.floor(Math.random()*6)+5}
function fresh(mode=s?.mode||'solo'){let targets=Array.from({length:TOTAL},rnd);return{mode,phase:1,targets,hideAt:targets.map(t=>Math.max(1,t-(1.2+Math.random()*1.8))),playing:false,score:0,round:1,combo:0,maxCombo:0,perfects:0,finished:false}}
function target(){return s.targets[s.round-1]}
function view(){E.target.textContent=s.finished?'GAME COMPLETE':`${s.mode==='versus'?`P${s.phase} · `:''}TARGET ${target()} SECONDS`;E.score.textContent=s.score;E.round.textContent=`${Math.min(s.round,TOTAL)} / ${TOTAL}`;E.combo.textContent=s.combo;for(const [k,m] of [['soloMode','solo'],['versusMode','versus']]){E[k].classList.toggle('is-selected',s.mode===m);E[k].setAttribute('aria-pressed',s.mode===m)}}
function progress(){E.bestScore.textContent=p.scores[0]?.score||0;E.bestNote.textContent=p.scores[0]?`${p.scores[0].label} · ${p.scores[0].date}`:'Finish a game to set a record.';E.leaderboard.innerHTML=Array.from({length:5},(_,i)=>`<li><span>#${i+1}</span><strong>${p.scores[i]?.score??'—'}</strong></li>`).join('');E.achievementList.innerHTML=badges.map(([id,a,b])=>`<li class="achievement ${p.achievements.includes(id)?'is-unlocked':''}">${a}<small>${b}</small></li>`).join('')}
function say(t,k=''){E.result.textContent=t;E.result.className=`result ${k}`}
let obscurePause,obscureSpin;
function clearTimerObscure(){clearTimeout(obscurePause);clearTimeout(obscureSpin);E.timer.classList.remove('is-hidden');E.timerFrame.classList.remove('is-obscured','is-blackout','is-paused','is-spinning');E.timerNote.hidden=true}
function obscureTimer(){if(E.timerFrame.classList.contains('is-obscured'))return;E.timerFrame.classList.add('is-obscured');E.timerNote.textContent='STICKERS APPROACHING…';E.timerNote.hidden=false;obscurePause=setTimeout(()=>{E.timerFrame.classList.add('is-blackout','is-paused');E.timer.classList.add('is-hidden');E.timerNote.textContent='TIMER LOST…';obscureSpin=setTimeout(()=>{E.timerFrame.classList.remove('is-paused');E.timerFrame.classList.add('is-spinning');E.timerNote.textContent='TIMER LOST — stop when you think the target time has arrived.'},560)},1050)}
function start(){if(s.finished)return;s.playing=true;s.start=performance.now();E.mainButton.textContent='STOP';E.timer.textContent='0.00';clearTimerObscure();E.targetChange.hidden=true;say('Watch the timer — the stickers will get in your way at a random moment.');requestAnimationFrame(tick)}
function tick(now){if(!s.playing)return;let time=(now-s.start)/1000;E.timer.textContent=time.toFixed(2);if(time>=s.hideAt[s.round-1])obscureTimer();sendRivalState(time);requestAnimationFrame(tick)}
function rate(d){if(d<.005)return['PERFECT!',100,'is-perfect',1,1];if(d<.1)return['GREAT!',80,'is-great',1,0];if(d<.3)return['GOOD',50,'is-great',0,0];if(d<.5)return['BAD',30,'is-miss',0,0];return['MISS',2,'is-miss',0,0]}
function finish(){let out={score:s.score,maxCombo:s.maxCombo,perfects:s.perfects};if(!p.achievements.includes('first'))p.achievements.push('first');if(out.score>=300&&!p.achievements.includes('score'))p.achievements.push('score');if(out.maxCombo>=3&&!p.achievements.includes('combo'))p.achievements.push('combo');if(out.perfects&&!p.achievements.includes('perfect'))p.achievements.push('perfect');if(s.mode==='versus'&&s.phase===1){s.player1Score=out.score;s.phase=2;s.score=0;s.round=1;s.combo=0;s.maxCombo=0;s.perfects=0;say(`PLAYER 1: ${out.score} POINTS — PLAYER 2, YOUR TURN.`,'is-great');return}p.scores.push({score:out.score,label:s.mode==='versus'?`P${s.phase}`:'SOLO',date:new Date().toLocaleDateString()});p.scores.sort((a,b)=>b.score-a.score);p.scores=p.scores.slice(0,5);save();progress();s.finished=true;E.mainButton.disabled=true;const versus=s.mode==='versus';const winner=out.score===s.player1Score?'DRAW':out.score>s.player1Score?'PLAYER 2 WINS':'PLAYER 1 WINS';say(versus?`${winner} · P1 ${s.player1Score} / P2 ${out.score}`:`GAME OVER — ${out.score} POINTS · ${out.perfects} PERFECT${out.perfects===1?'':'S'}`,'is-perfect')}
function stop(){if(!s.playing)return;s.playing=false;let time=(performance.now()-s.start)/1000,d=Math.abs(target()-time),r=rate(d);s.score+=r[1];s.combo=r[3]?s.combo+1:0;s.maxCombo=Math.max(s.maxCombo,s.combo);s.perfects+=r[4];clearTimerObscure();E.timer.textContent=time.toFixed(2);E.mainButton.textContent='START';say(`${r[0]} +${r[1]} · OFF BY ${d.toFixed(2)}s`,r[2]);s.round++;if(s.round>TOTAL)finish();else{E.targetChange.textContent=`NEXT ROUND · NEW TARGET: ${target()} SECONDS`;E.targetChange.hidden=false}view();lastRivalBroadcast=0;sendRivalState(time)}
function reset(){s=fresh(s?.mode);E.mainButton.disabled=false;E.mainButton.textContent='START';E.timer.textContent='0.00';clearTimerObscure();E.targetChange.hidden=true;say(s.mode==='versus'?'Player 1 starts. Both players receive the same targets; the stickers move at a random moment.':'Press START. The stickers move at a random moment each round.');view()}
function mode(m){if(!s.playing){s=fresh(m);reset()}}
E.mainButton.onclick=()=>s.playing?stop():start();E.restartButton.onclick=reset;E.soloMode.onclick=()=>mode('solo');E.versusMode.onclick=()=>mode('versus');E.shareButton.onclick=async()=>{const share={title:'THERMOREL',text:'Can you beat my hidden-timer score?',url:location.href};try{if(navigator.share)await navigator.share(share);else{await navigator.clipboard.writeText(location.href);E.shareButton.textContent='COPIED!';setTimeout(()=>E.shareButton.textContent='↗ SHARE',1300)}}catch{}};document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&e.target===document.body){e.preventDefault();E.mainButton.click()}});reset();progress();
function code(){return Array.from({length:6},()=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*32)]).join('')}
function roomMsg(t){E.roomStatus.textContent=t}
async function createRoom(){if(!db)return roomMsg('Online mode is loading.');const room=code(),targets=Array.from({length:TOTAL},rnd);const {error}=await db.from('rooms').insert({code:room,targets,status:'waiting'});if(error)return roomMsg('Could not create room. Try again.');s.mode='versus';reset();s.targets=targets;view();E.roomCode.value=room;roomMsg(`ROOM ${room} CREATED — share this code.`);db.channel('room-'+room).on('postgres_changes',{event:'UPDATE',schema:'public',table:'rooms',filter:'code=eq.'+room},p=>roomMsg(p.new.status==='playing'?'OPPONENT JOINED — START!':'Room updated.')).subscribe()}
async function joinRoom(){if(!db)return roomMsg('Online mode is loading.');const room=E.roomCode.value.trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(room))return roomMsg('Enter a 6-digit code.');const {data,error}=await db.from('rooms').update({status:'playing',updated_at:new Date().toISOString()}).eq('code',room).select().single();if(error||!data)return roomMsg('Room not found.');s.targets=data.targets; s.mode='versus'; reset(); s.targets=data.targets; roomMsg('JOINED! Same targets loaded — START!')}
E.mainButton.onclick=()=>s.playing?stop():start();E.restartButton.onclick=reset;E.soloMode.onclick=()=>mode('solo');E.versusMode.onclick=()=>mode('versus');E.createRoom.onclick=createRoom;E.joinRoom.onclick=joinRoom;E.roomCode.oninput=()=>E.roomCode.value=E.roomCode.value.toUpperCase();E.shareButton.onclick=async()=>{const share={title:'THERMOREL',text:'Can you beat my hidden-timer score?',url:location.href};try{if(navigator.share)await navigator.share(share);else{await navigator.clipboard.writeText(location.href);E.shareButton.textContent='COPIED!';setTimeout(()=>E.shareButton.textContent='↗ SHARE',1300)}}catch{}};document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&e.target===document.body){e.preventDefault();E.mainButton.click()}});reset();progress();
let loginMode=false;function account(){try{return JSON.parse(localStorage.getItem(ACCOUNT_KEY))}catch{return null}}function renderAccount(){const a=account();E.accountTitle.textContent=loginMode?'LOG IN':'CREATE ACCOUNT';E.accountCopy.textContent=loginMode?'Enter your nickname and PIN to continue.':'Pick a nickname and a 4-digit PIN. No email needed.';E.accountSubmit.textContent=loginMode?'LOG IN':'CREATE & PLAY';E.accountToggle.textContent=loginMode?'New player? CREATE ACCOUNT':'Already have an account? LOG IN';E.playerName.value=loginMode&&a?a.name:'';E.playerPin.value='';E.accountError.textContent=''}function openAccount(){loginMode=!!account();renderAccount();if(!E.accountDialog.open)E.accountDialog.showModal()}function submitAccount(e){e.preventDefault();const name=E.playerName.value.trim(),pin=E.playerPin.value;if(!name||!/^\d{4}$/.test(pin))return E.accountError.textContent='Enter a nickname and a 4-digit PIN.';const a=account();if(loginMode&&(!a||a.name!==name||a.pin!==pin))return E.accountError.textContent='Nickname or PIN is incorrect.';if(!loginMode)localStorage.setItem(ACCOUNT_KEY,JSON.stringify({name,pin}));E.accountDialog.close();E.accountButton.textContent=name.toUpperCase()}E.accountButton.onclick=openAccount;E.accountForm.addEventListener('submit',submitAccount);E.accountToggle.onclick=()=>{loginMode=!loginMode;renderAccount()};const currentAccount=account();if(currentAccount)E.accountButton.textContent=currentAccount.name.toUpperCase();else setTimeout(openAccount,250);document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&e.target===document.body){e.preventDefault();E.mainButton.click()}});reset();progress();
E.progressToggle.onclick=()=>{const open=E.metaBoard.hidden;E.metaBoard.hidden=!open;E.progressToggle.setAttribute('aria-expanded',String(open));E.progressToggle.textContent=open?'▴ PROGRESS':'▾ PROGRESS'};
function scheduleArtMotion(){if(!E.artSticker)return;setTimeout(()=>{if(!document.body.classList.contains('online-playing')){E.artSticker.currentTime=0;E.artSticker.play().catch(scheduleArtMotion)}else scheduleArtMotion()},18000+Math.random()*26000)}
if(E.artSticker){E.artSticker.addEventListener('ended',scheduleArtMotion,{once:false});scheduleArtMotion()}

let onlineRoom='',onlineRole='',onlineTargets=[],onlineChannel,onlineStartAt=0,lastRivalBroadcast=0,createRequest=0;
function safePlayerName(){return (account()?.name||'PLAYER').replace(/[|:]/g,'').slice(0,12)||'PLAYER'}
function packRoom(stage,host='',guest='',startAt=''){return [stage,encodeURIComponent(host),encodeURIComponent(guest),startAt].join('|')}
function unpackRoom(status=''){const [stage='waiting',host='',guest='',startAt='']=status.split('|');return{stage,host:decodeURIComponent(host||''),guest:decodeURIComponent(guest||''),startAt:Number(startAt)||0}}
function subscribeOnlineRoom(){onlineChannel?.unsubscribe?.();onlineChannel=db.channel('online-'+onlineRoom).on('broadcast',{event:'rival-state'},event=>renderRivalState(event.payload)).on('postgres_changes',{event:'UPDATE',schema:'public',table:'rooms',filter:'code=eq.'+onlineRoom},event=>syncOnlineRoom(event.new)).subscribe()}
function updateLobby(info){E.lobbyCode.textContent=onlineRoom;E.hostPlayer.textContent=`HOST · ${info.host||'PLAYER'}`;E.guestPlayer.textContent=info.guest?`GUEST · ${info.guest}`:'GUEST · WAITING FOR PLAYER';const ready=!!info.guest;E.lobbyStatus.textContent=ready?'PLAYERS READY':'WAITING FOR PLAYER';E.lobbyHelp.textContent=ready?'Host can start the match.':'Share this room code with your friend.';E.gameStart.hidden=!(onlineRole==='host'&&ready)}
function showLobby(info){document.body.classList.remove('online-playing');document.body.classList.add('online-lobby-open');E.onlineOverlay.hidden=true;E.onlineLobby.hidden=false;updateLobby(info)}
function showOnlineGame(info={}){document.body.classList.remove('online-lobby-open');document.body.classList.add('online-playing');E.onlineLobby.hidden=true;s.mode='versus';reset();s.targets=onlineTargets;view();E.opponentName.textContent=onlineRole==='host'?(info.guest||'OPPONENT'):(info.host||'OPPONENT');E.opponentTimer.textContent='0.00';E.opponentScore.textContent='0';E.opponentRound.textContent='1 / 5';onlineStartAt=info.startAt||Date.now()+5000;E.mainButton.disabled=true;E.mainButton.textContent='SYNCING';const countdown=()=>{const left=Math.max(0,onlineStartAt-Date.now());say(left?`MATCH STARTS IN ${(left/1000).toFixed(1)}…`:'GO!','is-perfect');if(left)return setTimeout(countdown,80);E.mainButton.disabled=false;start()};countdown()}
function syncOnlineRoom(room){const info=unpackRoom(room.status);if(room.targets)onlineTargets=room.targets;if(info.stage==='playing'){showOnlineGame(info);return}showLobby(info)}
function openOnline(){E.onlineOverlay.hidden=false;E.onlineChoice.hidden=false;E.onlineLoadingScreen.hidden=true;E.onlineJoinScreen.hidden=true;E.onlineError.textContent=''}
function closeOnline(){createRequest++;E.onlineOverlay.hidden=true;E.onlineLoadingScreen.hidden=true;E.onlineJoinScreen.hidden=true;E.onlineChoice.hidden=false}
async function createOnline(){if(!db){E.onlineError.textContent='Online service is loading.';return}const request=++createRequest,host=safePlayerName(),room=code(),targets=Array.from({length:TOTAL},rnd);E.onlineChoice.hidden=true;E.onlineJoinScreen.hidden=true;E.onlineLoadingScreen.hidden=false;const {error}=await db.from('rooms').insert({code:room,targets,status:packRoom('waiting',host)});if(request!==createRequest){if(!error)await db.from('rooms').delete().eq('code',room);return}if(error){E.onlineLoadingScreen.hidden=true;E.onlineChoice.hidden=false;E.onlineError.textContent='Could not create room. Try again.';return}onlineRoom=room;onlineRole='host';onlineTargets=targets;subscribeOnlineRoom();showLobby({stage:'waiting',host,guest:''})}
function cancelCreate(){createRequest++;E.onlineLoadingScreen.hidden=true;E.onlineChoice.hidden=false}
function showJoinScreen(){E.onlineChoice.hidden=true;E.onlineJoinScreen.hidden=false;E.onlineRoomCode.value='';E.onlineError.textContent=''}
async function joinOnline(){if(!db){E.onlineError.textContent='Online service is loading.';return}const room=E.onlineRoomCode.value.trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(room)){E.onlineError.textContent='Enter a 6-digit code.';return}const {data,error}=await db.from('rooms').select('status,targets').eq('code',room).single();if(error||!data){E.onlineError.textContent='Room not found.';return}const info=unpackRoom(data.status);if(info.stage==='playing'||info.guest){E.onlineError.textContent='This room is already in a match.';return}const guest=safePlayerName();const {error:updateError}=await db.from('rooms').update({status:packRoom('ready',info.host,guest),updated_at:new Date().toISOString()}).eq('code',room);if(updateError){E.onlineError.textContent='Could not join. Try again.';return}onlineRoom=room;onlineRole='guest';onlineTargets=data.targets;subscribeOnlineRoom();showLobby({stage:'ready',host:info.host,guest})}
async function startOnline(){if(onlineRole!=='host'||!onlineRoom)return;const data=unpackRoom(`ready|${encodeURIComponent(E.hostPlayer.textContent.replace('HOST · ',''))}|${encodeURIComponent(E.guestPlayer.textContent.replace('GUEST · ',''))}`),startAt=Date.now()+5000;await db.from('rooms').update({status:packRoom('playing',data.host,data.guest,startAt),updated_at:new Date().toISOString()}).eq('code',onlineRoom);showOnlineGame({...data,startAt})}
function exitLobby(){onlineChannel?.unsubscribe?.();onlineChannel=null;onlineRoom='';document.body.classList.remove('online-lobby-open','online-playing');E.onlineLobby.hidden=true}
E.onlineButton.onclick=openOnline;E.onlineClose.onclick=closeOnline;E.onlineCreate.onclick=createOnline;E.onlineCreateCancel.onclick=cancelCreate;E.onlineJoin.onclick=showJoinScreen;E.joinBack.onclick=()=>{E.onlineJoinScreen.hidden=true;E.onlineChoice.hidden=false};E.onlineJoinConfirm.onclick=joinOnline;E.onlineRoomCode.oninput=()=>E.onlineRoomCode.value=E.onlineRoomCode.value.toUpperCase();E.gameStart.onclick=startOnline;E.lobbyExit.onclick=exitLobby;
function sendRivalState(time){if(!onlineChannel||!document.body.classList.contains('online-playing')||performance.now()-lastRivalBroadcast<220)return;lastRivalBroadcast=performance.now();onlineChannel.send({type:'broadcast',event:'rival-state',payload:{name:safePlayerName(),time:time.toFixed(2),score:s.score,round:`${Math.min(s.round,TOTAL)} / ${TOTAL}`}})}
function renderRivalState(state){if(!state||state.name===safePlayerName())return;E.opponentName.textContent=state.name||'OPPONENT';E.opponentTimer.textContent=state.time||'0.00';E.opponentScore.textContent=state.score??0;E.opponentRound.textContent=state.round||'1 / 5'}
