(() => {
  const db = window.supabase?.createClient('https://zzowexahijdlupfurgcs.supabase.co','sb_publishable_jvtfEALEbtnzKM5YLivUAQ_CO3TAZXF');
  const key = 'thermorel-social-code-v1';
  const code = localStorage.getItem(key) || (() => { const value = Array.from({length:8}, () => 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(Math.random()*32)]).join(''); localStorage.setItem(key,value); return value; })();
  const account = () => { try { return JSON.parse(localStorage.getItem('thermorel-account-v2')) || {}; } catch { return {}; } };
  const name = () => (account().name || 'PLAYER').slice(0,12);
  const developer = () => name().toUpperCase() === 'RIHI1';
  const esc = value => String(value || '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const top = document.querySelector('.top-controls');
  const addButton = (id,label) => { const button=document.createElement('button'); button.id=id; button.type='button'; button.className='online-button community-button'; button.textContent=label; top?.prepend(button); return button; };
  const feedbackButton=addButton('feedbackButton','✦ FEEDBACK'), friendsButton=addButton('friendsButton','◎ FRIENDS'), meButton=addButton('meButton','◉ ME');
  const shell=document.createElement('div'); shell.className='community-overlay'; shell.hidden=true;
  shell.innerHTML='<section class="community-card"><button class="community-close" type="button" aria-label="Close">×</button><div class="community-tabs"><button data-tab="feedback">FEEDBACK</button><button data-tab="friends">FRIENDS</button><button data-tab="me">ME</button></div><div id="communityBody"></div></section>';
  document.body.append(shell);
  const body=shell.querySelector('#communityBody');
  const open=tab=>{shell.hidden=false; render(tab)}; const close=()=>shell.hidden=true;
  shell.querySelector('.community-close').onclick=close; feedbackButton.onclick=()=>open('feedback'); friendsButton.onclick=()=>open('friends'); meButton.onclick=()=>open('me');
  const notice = text => `<p class="community-note">${esc(text)}</p>`;
  async function feedback(){
    body.innerHTML='<p class="brand-kicker">KEEP THERMOREL SIMPLE</p><h2>FEEDBACK</h2><p class="community-copy">「シンプルさ」と「複雑さ」を先に確認してから、BETAへ進めます。</p><form id="feedbackForm"><textarea id="feedbackText" maxlength="500" placeholder="アイデアを書いてね" required></textarea><label>これを足すとシンプルではなくなる？<select id="simpleVote"><option value="no">NO</option><option value="maybe">MAYBE</option><option value="yes">YES</option></select></label><label>複雑になる？<select id="complexVote"><option value="no">NO</option><option value="maybe">MAYBE</option><option value="yes">YES</option></select></label><button class="online-action create">SEND FEEDBACK</button></form><div id="feedbackList">LOADING…</div>';
    body.querySelector('#feedbackForm').onsubmit=async event=>{event.preventDefault(); const text=body.querySelector('#feedbackText').value.trim(); const {error}=await db.from('feedback').insert({author_id:code,author_name:name(),body:text,simplicity:body.querySelector('#simpleVote').value,complexity:body.querySelector('#complexVote').value}); if(error) return alert('Feedback storage is preparing. Please try again.'); feedback();};
    const {data,error}=await db.from('feedback').select('*').order('created_at',{ascending:false}).limit(30); if(error){body.querySelector('#feedbackList').innerHTML=notice('Feedback storage is preparing.');return}
    const ids=(data||[]).map(item=>item.id), {data:reactions}=ids.length?await db.from('feedback_reactions').select('*').in('feedback_id',ids):{data:[]};
    body.querySelector('#feedbackList').innerHTML=(data||[]).map(item=>{const count=(reactions||[]).filter(reaction=>reaction.feedback_id===item.id).length; return `<article class="feedback-item"><strong>${esc(item.status.toUpperCase())}</strong><p>${esc(item.body)}</p><small>SIMPLE? ${item.simplicity.toUpperCase()} · COMPLEX? ${item.complexity.toUpperCase()} · ${count} OK</small><div><button data-ok="${item.id}">👍 OK</button>${developer()&&item.status==='review'?`<button data-beta="${item.id}">BETA</button>`:''}${developer()&&item.status==='beta'&&count>=5?`<button data-final="${item.id}">MAKE FINAL</button>`:''}</div></article>`}).join('')||notice('まだFeedbackはありません。');
    body.querySelectorAll('[data-ok]').forEach(button=>button.onclick=async()=>{await db.from('feedback_reactions').upsert({feedback_id:+button.dataset.ok,reactor_id:code,reaction:'ok'});feedback()});
    body.querySelectorAll('[data-beta]').forEach(button=>button.onclick=async()=>{await db.from('feedback').update({status:'beta',developer_ok:true}).eq('id',+button.dataset.beta);feedback()});
    body.querySelectorAll('[data-final]').forEach(button=>button.onclick=async()=>{await db.from('feedback').update({status:'final',developer_ok:true}).eq('id',+button.dataset.final);feedback()});
  }
  async function friends(){ body.innerHTML=`<p class="brand-kicker">YOUR FRIEND CODE</p><h2>${code}</h2><p class="community-copy">友だちにこのコードを送ろう。</p><form id="friendForm"><input id="friendCode" maxlength="8" placeholder="FRIEND CODE" required><button class="online-action create">ADD FRIEND</button></form><form id="directForm"><input id="directCode" maxlength="8" placeholder="FRIEND CODE TO MESSAGE" required><input id="directText" maxlength="400" placeholder="MESSAGE" required><button class="online-action join">SEND MESSAGE</button></form><div id="friendList">LOADING…</div><div id="directMessages"></div>`; body.querySelector('#friendForm').onsubmit=async event=>{event.preventDefault();const target=body.querySelector('#friendCode').value.trim().toUpperCase();if(target===code)return;await db.from('friendships').insert({requester_id:code,requester_name:name(),recipient_code:target});body.querySelector('#friendCode').value='';}; body.querySelector('#directForm').onsubmit=async event=>{event.preventDefault();const target=body.querySelector('#directCode').value.trim().toUpperCase(),text=body.querySelector('#directText').value.trim();await db.from('messages').insert({scope:'direct',recipient_code:target,sender_id:code,sender_name:name(),body:text});body.querySelector('#directText').value='';loadDirect(target)}; const {data,error}=await db.from('friendships').select('*').or(`requester_id.eq.${code},recipient_code.eq.${code}`).order('created_at',{ascending:false}).limit(30); body.querySelector('#friendList').innerHTML=error?notice('Friends storage is preparing.'):(data||[]).map(friend=>`<article class="feedback-item"><strong>${friend.status.toUpperCase()}</strong><p>${esc(friend.requester_name)} · ${esc(friend.requester_id===code?friend.recipient_code:friend.requester_id)}</p>${friend.recipient_code===code&&friend.status==='requested'?`<button data-accept="${friend.id}">ACCEPT</button>`:''}</article>`).join('')||notice('まだフレンドはいません。'); body.querySelectorAll('[data-accept]').forEach(button=>button.onclick=async()=>{await db.from('friendships').update({status:'accepted'}).eq('id',+button.dataset.accept);friends()}); async function loadDirect(target){const {data}=await db.from('messages').select('*').eq('scope','direct').or(`recipient_code.eq.${code},recipient_code.eq.${target}`).order('created_at',{ascending:false}).limit(20);body.querySelector('#directMessages').innerHTML=(data||[]).map(message=>`<article class="feedback-item"><strong>${esc(message.sender_name)}</strong><p>${esc(message.body)}</p></article>`).join('')} }
  function me(){body.innerHTML='<p class="brand-kicker">ME</p><h2>RIHIRO SAKATA</h2><p class="community-copy">いろんなゲーム作ってるよー<br>小学生だよー<br>※このゲームはAIを使用しています<br>なんか案があったらFeedbackで教えてね</p>'}
  function render(tab){shell.querySelectorAll('[data-tab]').forEach(button=>button.classList.toggle('is-selected',button.dataset.tab===tab));shell.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>render(button.dataset.tab));({feedback,friends,me})[tab]();}
  const chat=document.createElement('section'); chat.className='room-chat'; chat.hidden=true; chat.innerHTML='<button id="roomChatToggle" type="button">▣ CHAT</button><div id="roomChatBox" hidden><div id="roomMessages"></div><form id="roomMessageForm"><input id="roomMessageText" maxlength="400" placeholder="MESSAGE" required><button>SEND</button></form></div>'; document.body.append(chat);
  const room=()=>new URLSearchParams(location.hash.split('&').slice(1).join('&')).get('pass')?.toUpperCase();
  async function messages(){const pass=room();if(!pass)return;const {data}=await db.from('messages').select('*').eq('scope','room').eq('room_code',pass).order('created_at',{ascending:true}).limit(40);chat.querySelector('#roomMessages').innerHTML=(data||[]).map(message=>`<p><b>${esc(message.sender_name)}</b> ${esc(message.body)}</p>`).join('')||'<p>NO MESSAGES</p>'}
  chat.querySelector('#roomChatToggle').onclick=()=>{const box=chat.querySelector('#roomChatBox');box.hidden=!box.hidden;if(!box.hidden)messages()}; chat.querySelector('#roomMessageForm').onsubmit=async event=>{event.preventDefault();const pass=room(),input=chat.querySelector('#roomMessageText');if(!pass)return;await db.from('messages').insert({scope:'room',room_code:pass,sender_id:code,sender_name:name(),body:input.value.trim()});input.value='';messages()};
  setInterval(()=>{const inRoom=location.hash.startsWith('#room&pass=');chat.hidden=!inRoom;if(inRoom&&!chat.querySelector('#roomChatBox').hidden)messages()},4000);
  setInterval(async()=>{const {data}=await db.from('feedback').select('id,body').eq('status','beta');const seen=JSON.parse(localStorage.getItem('thermorel-seen-beta')||'[]'),fresh=(data||[]).filter(item=>!seen.includes(item.id));if(fresh.length){alert(`NEW BETA: ${fresh.map(item=>item.body).join(' / ')}`);localStorage.setItem('thermorel-seen-beta',JSON.stringify((data||[]).map(item=>item.id))) }},12000);
})();
